version: '3.9'

services:
  postgres:
    image: postgres:17.2
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ~/pgdata:/var/lib/postgresql/data/pgdata